### ISSUE TITLE
Support Sequelize v5

### ISSUE THREAD

**Issue by g00ds0n** [node-casbin/sequelize-adapter#14]
I can't call addPolicy when using Sequelize v5. I get the following error:

```
     TypeError: sequelize_1.Model[(staticMethodPrefix + "conformOptions")] is not a function
      at Function.BaseModel.prepareInstantiationOptions (node_modules/sequelize-typescript/lib/models/BaseModel.js:97:69)
      at new Model (node_modules/sequelize-typescript/lib/models/v4/Model.js:8:45)
      at new CasbinRule (node_modules/casbin-sequelize-adapter/lib/casbinRule.js:26:18)
      at new <anonymous> (node_modules/casbin-sequelize-adapter/lib/adapter.js:28:12)
      at SequelizeAdapter.savePolicyLine (node_modules/casbin-sequelize-adapter/lib/adapter.js:122:22)
      at SequelizeAdapter.<anonymous> (node_modules/casbin-sequelize-adapter/lib/adapter.js:175:31)
      at Generator.next (<anonymous>)
      at .../node_modules/casbin-sequelize-adapter/lib/adapter.js:20:71
      at new WrappedPromise (node_modules/async-listener/es6-wrapped-promise.js:13:18)
      at __awaiter (node_modules/casbin-sequelize-adapter/lib/adapter.js:16:12)
      at SequelizeAdapter.addPolicy (node_modules/casbin-sequelize-adapter/lib/adapter.js:174:16)
      at Context.<anonymous> (test/controller/attachment_controller_test.js:73:27)
```

**Comment by nodece** [comment]
@g00ds0n Thank you for make this issue, It will work in next version.

**Comment by krayis** [comment]
Any update on this issue?

**Comment by nodece** [comment]
@krayis OMG, I forgot! I submitted a PR: https://github.com/node-casbin/sequelize-adapter/pull/15.

**Comment by hsluoyz** [comment]
Hi @g00ds0n @krayis , we encountered build error in our Sequelize v5 PR: https://github.com/node-casbin/sequelize-adapter/pull/15  can you help us fix it?

**Comment by hsluoyz** [comment]
@nodece please release a new version.

**Comment by nodece** [comment]
Thank for @g00ds0n @krayis the report, sequelize-adapter v2.0.0 has been released.
