### ISSUE TITLE
TypeError: Cannot read property 'getQueryInterface' of undefined

### ISSUE THREAD

**Issue by apsnaidu** [node-casbin/sequelize-adapter#32]
Using `sequelize-adapter` with CommonJS module complains about sequelize object being undefined.
Here is the stack trace:
```
/Repos/config-service/node_modules/sequelize/lib/model.js:55
    return this.sequelize.getQueryInterface();
                          ^

TypeError: Cannot read property 'getQueryInterface' of undefined
    at Function.get queryInterface [as queryInterface] (/Repos/config-service/node_modules/sequelize/lib/model.js:55:27)
    at isFunctionMember (/Repos/config-service/node_modules/sequelize-typescript/dist/model/model/model.js:99:25)
    at object_1.getAllPropertyNames.filter.key (/Repos/config-service/node_modules/sequelize-typescript/dist/model/model/model.js:96:5)
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/Repos/config-service/node_modules/sequelize-typescript/dist/model/model/model.js:95:6)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Here is the code being run:
```
const casbin = require("casbin");
const { SequelizeAdapter } = require("casbin-sequelize-adapter");
(async () => {
  const a = await SequelizeAdapter.newAdapter({
    host: "localhost",
    port: "3306",
    username: "root",
    password: "",
    database: "test",
    dialect: "mysql",
  });

  const e = await casbin.newEnforcer("../model.conf", a);
  e.enforce("alice", "data1", "read");
})();
```

node version: v14.8.0
 "casbin": "^5.1.3",
 "casbin-sequelize-adapter": "^2.1.0",

**Comment by nodece** [comment]
@apsnaidu could you provide the sequelize version?

**Comment by apsnaidu** [comment]
@nodece - sequelize version is 6.3.4

**Comment by nodece** [comment]
@apsnaidu because we are using https://github.com/RobinBuschmann/sequelize-typescript, but it only supports sequelize@v5, so your project doesn't work. 

could you downgrade to sequelize@v5?

**Comment by apsnaidu** [comment]
Thanks for the prompt response. Sure, we will make use of sequelize v5 for now.
